FROM golang:alpine as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o fenix .

FROM alpine:3.10.2
RUN apk update \
&& apk upgrade \
&& apk add --no-cache ca-certificates && \
update-ca-certificates 2>/dev/null || true && \
addgroup -S fenix && adduser -S -G fenix fenix

USER fenix
COPY --from=builder /app/fenix /fenix
ENTRYPOINT ["/fenix"]