{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fenix.serviceAccountName" . }}
  labels:
{{ include "fenix.labels" . | indent 4 }}
{{- end -}}
